spring:
  datasource:
    url: jdbc:mysql://pawpalsdatabase:3306/pawpals
    username: pawpals
    password: pawpals
  jpa:
    show-sql: true
    database: mysql
server:
  servlet:
    context-path: /pawpals
